CREATE TABLE [CONFIG_ALLOCATION_TYPE] (
    [ALLOCATION_TYPE_ID] int NOT NULL IDENTITY,
    [ALLOCATION_TYPE] nvarchar(50) NULL,
    [ALLOCATION_DESCRIPTION] nvarchar(500) NULL,
    [ALLOCATION_CRITERIA_SQL] nvarchar(max) NULL,
    CONSTRAINT [PK_ALLOCATION_TYPE_ID] PRIMARY KEY ([ALLOCATION_TYPE_ID]) WITH (FILLFACTOR = 90)
);
GO


CREATE TABLE [CONFIG_ICM_ADMIN_GROUPS] (
    [ICM_GROUP_ID] int NOT NULL IDENTITY,
    [GROUP_DESC] varchar(150) NULL,
    CONSTRAINT [PK_ICM_GROUP_ID] PRIMARY KEY ([ICM_GROUP_ID]) WITH (FILLFACTOR = 90)
);
GO


CREATE TABLE [CONFIG_ICM_ADMIN_SCREENS] (
    [ICM_SCREEN_ID] int NOT NULL IDENTITY,
    [SCREEN_NAME] varchar(200) NULL,
    [SCREEN_TITLE] varchar(200) NULL,
    [GROUP_ID] int NULL,
    CONSTRAINT [PK_ICM_SCREEN_ID] PRIMARY KEY ([ICM_SCREEN_ID]) WITH (FILLFACTOR = 90)
);
GO


CREATE TABLE [CONFIG_ICM_ADMIN_USERS] (
    [ICM_USER_ID] int NOT NULL IDENTITY,
    [USERNAME] varchar(150) NULL,
    [USER_FNAME] varchar(100) NULL,
    [USER_SNAME] varchar(100) NULL,
    [USER_GROUPID] int NULL,
    CONSTRAINT [PK_ICM_USER_ID] PRIMARY KEY ([ICM_USER_ID]) WITH (FILLFACTOR = 90)
);
GO


CREATE TABLE [CONFIG_ORDER_STATUS] (
    [STATUS_CD] nvarchar(200) NULL,
    [BU_NAME] nvarchar(60) NULL,
    [REVENUE] bit NULL DEFAULT CAST(0 AS bit),
    [COMMISSION] bit NULL DEFAULT CAST(0 AS bit)
);
GO


CREATE TABLE [CONFIG_PAYPLAN_ENHANCEMENT] (
    [ENHANCEMENT_ID] int NOT NULL IDENTITY,
    [PAYPLAN_TYPE] varchar(5) NULL,
    [ENHANCEMENT_DESC] varchar(50) NULL,
    [ENHANCEMENT_CRITERIA_SQL] nvarchar(max) NULL,
    [ENHANCEMENT_RATE] numeric(18,7) NULL,
    CONSTRAINT [PK_CONFIG_PAYPLAN_ENHANCEMENT] PRIMARY KEY ([ENHANCEMENT_ID]) WITH (FILLFACTOR = 90)
);
GO


CREATE TABLE [CONFIG_PAYPLAN_RATE_TABLES] (
    [RATE_TABLE_ID] int NOT NULL IDENTITY,
    [PAY_PLAN_TYPE] nvarchar(5) NULL,
    [RATE_TABLE_DESC] varchar(200) NULL,
    CONSTRAINT [PK_CONFIG_TABLE2] PRIMARY KEY ([RATE_TABLE_ID]) WITH (FILLFACTOR = 90)
);
GO


CREATE TABLE [CONFIG_PAYPLAN_TYPE] (
    [PAY_PLAN_TYPE] varchar(5) NULL,
    [DEFAULT_RATE_TABLE] int NULL,
    [PAY_PLAN_DESC] varchar(50) NULL
);
GO


CREATE TABLE [CONFIG_PROCESSING_TYPE] (
    [payplan] nvarchar(2) NULL,
    [periodYear] nvarchar(4) NULL,
    [processingType] nvarchar(10) NULL
);
GO


CREATE TABLE [CONFIG_ROLLUP_TYPE] (
    [ROLLUP_TYPE_ID] int NOT NULL IDENTITY,
    [PAYPLAN_TYPE] nvarchar(5) NULL,
    [ROLLUP_TYPE] nvarchar(30) NULL,
    [ROLLUP_CRITERIA] nvarchar(max) NULL,
    [PERIOD_YEAR] nvarchar(4) NOT NULL DEFAULT (([dbo].[ufn_getSysParm]('PERIOD_YEAR'))),
    CONSTRAINT [PK_ROLLUP_TYPE_ID] PRIMARY KEY ([ROLLUP_TYPE_ID]) WITH (FILLFACTOR = 90)
);
GO


CREATE TABLE [CONFIG_SALES_PERIOD] (
    [PERIOD_YEAR] nchar(4) NULL,
    [PERIOD_MONTH] nchar(2) NULL,
    [PERIOD_START] datetime NULL,
    [PERIOD_END] datetime NULL
);
GO


CREATE TABLE [CONFIG_SYSTEM_PARAMETERS] (
    [PARAMETER_NAME] nvarchar(50) NOT NULL,
    [PARAMETER_VALUE] nvarchar(50) NULL,
    [PARAMETER_DESCRIPTION] nvarchar(500) NULL,
    CONSTRAINT [PK_CONFIG_SYSTEM_PARAMETERS] PRIMARY KEY ([PARAMETER_NAME])
);
GO


CREATE TABLE [DATA_BUSINESS_UNIT] (
    [DATA_BUSINESS_UNIT_ID] int NOT NULL IDENTITY,
    [ORDER_ID] nvarchar(15) NULL,
    [STATUS_CD] nvarchar(30) NULL,
    [STATUS_DT] datetime NULL,
    [BU_NAME] nvarchar(100) NULL,
    CONSTRAINT [PK_DATA_BUSINESS_UNIT_ID] PRIMARY KEY ([DATA_BUSINESS_UNIT_ID]) WITH (FILLFACTOR = 90)
);
GO


CREATE TABLE [DATA_CANCEL_REPLACE_SKIPPED_ORDER] (
    [DATA_CANCEL_REPLACE_SKIPPED_ORDER_ID] int NOT NULL IDENTITY,
    [ORDER_ROW_ID] nvarchar(30) NULL,
    [ORDER_NUMBER] nvarchar(30) NULL,
    [PERIOD_MONTH] nvarchar(2) NULL,
    [PERIOD_YEAR] nvarchar(4) NULL,
    [DATE_CREATED] datetime NOT NULL DEFAULT ((getdate()))
);
GO


CREATE TABLE [DATA_COMMISSION_PAYMENT] (
    [DATA_COMMISSION_PAYMENT_ID] int NOT NULL IDENTITY,
    [POSITION_ID] nvarchar(15) NULL,
    [EMPLOYEE_ID] nvarchar(30) NULL,
    [PAYMENT_SOURCE] varchar(150) NULL,
    [PAYMENT_DESCRIPTION] varchar(max) NULL,
    [ORDER_ID] nvarchar(30) NULL,
    [ENHANCEMENT_ID] int NULL,
    [PAYPLAN_RATE_ID] int NULL,
    [ADJUSTMENT_ID] int NULL,
    [PAYMENT_RATE] numeric(18,7) NULL,
    [PAYMENT_VALUE] numeric(18,7) NULL,
    [PAYMENT_WITHELD] bit NOT NULL,
    [PERIOD_MONTH] nvarchar(2) NOT NULL DEFAULT (([dbo].[ufn_getSysParm]('PERIOD_MONTH'))),
    [PERIOD_YEAR] nvarchar(4) NOT NULL DEFAULT (([dbo].[ufn_getSysParm]('PERIOD_YEAR'))),
    [DATE_CREATED] datetime NOT NULL DEFAULT ((getdate())),
    CONSTRAINT [PK_DATA_COMMISSION_PAYMENT_ID] PRIMARY KEY ([DATA_COMMISSION_PAYMENT_ID]) WITH (FILLFACTOR = 90)
);
GO


CREATE TABLE [DATA_CREDIT_ALLOCATION] (
    [DATA_CREDIT_ALLOCATION_ID] int NOT NULL IDENTITY,
    [POSITION_ID] nvarchar(30) NULL,
    [EMPLOYEE_ID] nvarchar(30) NULL,
    [CHILD_POSITION_ID] nvarchar(30) NULL,
    [ALLOCATION_SOURCE] nvarchar(30) NULL,
    [ORDER_ID] nvarchar(30) NULL,
    [ITEM_ID] nvarchar(30) NULL,
    [ADJUSTMENT_ID] int NULL,
    [ALLOCATION_TYPE_ID] int NULL,
    [ALLOCATION_LIST] numeric(22,7) NULL,
    [ALLOCATION_VALUE] numeric(22,7) NULL,
    [EXCLUDE_FROM_CALCS] nvarchar(1) NULL,
    [ROLLUP_PROCESSED] nvarchar(1) NULL DEFAULT N'N',
    [PERIOD_MONTH] nvarchar(2) NULL DEFAULT (([dbo].[ufn_getSysParm]('PERIOD_MONTH'))),
    [PERIOD_YEAR] nvarchar(4) NULL DEFAULT (([dbo].[ufn_getSysParm]('PERIOD_YEAR'))),
    [DATE_CREATED] datetime NULL DEFAULT ((getdate())),
    [PAYPLAN] nvarchar(max) NULL,
    CONSTRAINT [PK_DATA_CREDIT_ALLOCATION_ID] PRIMARY KEY ([DATA_CREDIT_ALLOCATION_ID]) WITH (FILLFACTOR = 90)
);
GO


CREATE TABLE [DATA_DEFAULT_TARGETS] (
    [DATA_DEFAULT_TARGETS_ID] int NOT NULL IDENTITY,
    [PAY_PLAN_TYPE] nvarchar(5) NULL,
    [EMPLOYEE_ID] nvarchar(30) NULL DEFAULT N'X',
    [ALLOCATION_TYPE_ID] int NULL,
    [ALLOCATION_DESCRIPTION] nvarchar(500) NULL,
    [TARGET_VALUE] numeric(22,7) NULL,
    [FIN_YEAR] nvarchar(4) NOT NULL DEFAULT (([dbo].[ufn_getSysParm]('PERIOD_YEAR'))),
    CONSTRAINT [PK_DATA_DEFAULT_TARGETS_ID] PRIMARY KEY ([DATA_DEFAULT_TARGETS_ID]) WITH (FILLFACTOR = 90)
);
GO


CREATE TABLE [DATA_EMPLOYEE_TARGETS] (
    [DATA_EMPLOYEE_TARGETS_ID] int NOT NULL IDENTITY,
    [EMPLOYEE_ID] nvarchar(30) NULL,
    [ALLOCATION_TYPE_ID] int NULL,
    [TARGET_VALUE] numeric(22,7) NULL,
    [PERIOD_MONTH] nvarchar(2) NOT NULL DEFAULT (([dbo].[ufn_getSysParm]('PERIOD_MONTH'))),
    [PERIOD_YEAR] nvarchar(4) NOT NULL DEFAULT (([dbo].[ufn_getSysParm]('PERIOD_YEAR'))),
    [DATE_CREATED] datetime NOT NULL DEFAULT ((getdate())),
    [PAYPLAN] varchar(3) NULL,
    CONSTRAINT [PK_DATA_EMPLOYEE_TARGETS] PRIMARY KEY ([DATA_EMPLOYEE_TARGETS_ID]) WITH (FILLFACTOR = 90)
);
GO


CREATE TABLE [DATA_EMPLOYEES] (
    [DATA_EMPLOYEES_ID] int NOT NULL IDENTITY,
    [ROW_ID] nvarchar(30) NULL,
    [FST_NAME] nvarchar(100) NULL,
    [LAST_NAME] nvarchar(100) NULL,
    [EMAIL_ADDR] nvarchar(200) NULL,
    [JOB_TITLE] nvarchar(150) NULL,
    [EMPLOYEE_NUMBER] nvarchar(100) NULL,
    [PR_HELD_POSTN_ID] nvarchar(30) NULL,
    [LOGIN] nvarchar(100) NULL,
    [DELETE_FLAG] int NULL DEFAULT 0,
    [DATE_CREATED] datetime NOT NULL DEFAULT ((getdate())),
    CONSTRAINT [PK_DATA_EMPLOYEES_ID] PRIMARY KEY ([DATA_EMPLOYEES_ID]) WITH (FILLFACTOR = 90)
);
DECLARE @defaultSchema AS sysname;
SET @defaultSchema = SCHEMA_NAME();
DECLARE @description AS sql_variant;
SET @description = N'Indicates whether EMPLOYEE has been deleted from the imported TMP_DATA_EMPLOYEES extract [1 = DELETED]';
EXEC sp_addextendedproperty 'MS_Description', @description, 'SCHEMA', @defaultSchema, 'TABLE', N'DATA_EMPLOYEES', 'COLUMN', N'DELETE_FLAG';
GO


CREATE TABLE [DATA_EXCLUDED_PRODUCTS] (
    [DATA_EXCLUDED_PRODUCTS_ID] int NOT NULL IDENTITY,
    [ITEM_ID] nvarchar(30) NULL,
    [PRODUCT_DESC] nvarchar(500) NULL,
    [PRODUCT_CODE] nvarchar(30) NULL,
    [PRODUCT_LEVEL_1] nvarchar(20) NULL,
    [PRODUCT_LEVEL_2] nvarchar(20) NULL,
    [PRODUCT_LEVEL_3] nvarchar(20) NULL,
    [PRODUCT_TYPE] nvarchar(80) NULL,
    [EXCLUDED] int NULL DEFAULT 1,
    [LEVEL_BASED] int NULL DEFAULT 0,
    CONSTRAINT [PK_DATA_EXCLUDED_PRODUCTS] PRIMARY KEY ([DATA_EXCLUDED_PRODUCTS_ID])
);
GO


CREATE TABLE [DATA_IMPRESS_COMMISSION_INCIDENT] (
    [DATA_IMPRESS_COMMISSION_INCIDENT_ID] int NOT NULL IDENTITY,
    [SF_ORDER_ID] nvarchar(15) NULL,
    [SF_EMPLOYEE_ID] nvarchar(30) NULL,
    [INCIDENT_DESCRIPTION] nvarchar(500) NULL,
    [PERIOD_MONTH] nvarchar(4) NULL,
    [PERIOD_YEAR] nvarchar(4) NULL,
    CONSTRAINT [DATA_IMPRESS_COMMISSION_INCIDENT_ID] PRIMARY KEY ([DATA_IMPRESS_COMMISSION_INCIDENT_ID]) WITH (FILLFACTOR = 90)
);
GO


CREATE TABLE [DATA_IMPRESS_SUBSCRIPTION_ORDER] (
    [DATA_IMPRESS_SUBSCRIPTION_ORDER_ID] int NOT NULL IDENTITY,
    [IM_ORDER_NUMBER] nvarchar(50) NULL,
    [SF_ORDER_NUMBER] nvarchar(50) NULL,
    [IM_ACCOUNT_NAME] nvarchar(50) NULL,
    [IM_ACCOUNT_NUMBER] nvarchar(50) NULL,
    [IM_PLAN_NAME] nvarchar(50) NULL,
    [IM_PLAN_TIER] nvarchar(50) NULL,
    [SF_EMPLOYEE_ID] nvarchar(50) NULL,
    [SF_SUBSCRIPTION_MONTHS_AMOUNT] int NULL,
    [SF_ANTICIPATED_USAGE] numeric(7,2) NULL,
    [SF_SUBSCRIPTION_PRICE] numeric(7,2) NULL,
    [SF_ORDER_STATUS] nvarchar(150) NULL,
    [SF_LAST_STATUS_UPDATE_TIME] datetime NULL,
    [IM_PRICE_PER_USAGE_ITEM] numeric(7,2) NULL,
    [IM_ACTUAL_USAGE] int NULL,
    [PROCESSED] int NULL
);
GO


CREATE TABLE [DATA_MANUAL_ADJUSTMENTS] (
    [ADJUSTMENT_ID] int NOT NULL IDENTITY,
    [ADJUSTMENT_TYPE] nvarchar(20) NULL,
    [POSITION_ID] nvarchar(30) NULL,
    [EMPLOYEE_ID] nvarchar(30) NULL,
    [ORDER_ID] nvarchar(30) NULL,
    [ALLOCATION_TYPE_ID] int NULL,
    [ALLOCATION_VALUE] numeric(22,7) NULL,
    [ALLOCATION_LIST] numeric(22,7) NULL,
    [EXCLUDE_FROM_CALCS] nvarchar(1) NULL,
    [ADJUSTMENT_REASON] nvarchar(max) NULL,
    [ADJUSTMENT_DATE] datetime NOT NULL DEFAULT ((getdate())),
    [ADJUSTMENT_BY] nvarchar(100) NOT NULL DEFAULT ((suser_sname())),
    [ADJUSTMENT_PROCESSED] nvarchar(1) NOT NULL DEFAULT N'N',
    [PERIOD_MONTH] nvarchar(2) NOT NULL DEFAULT (([dbo].[ufn_getSysParm]('PERIOD_MONTH'))),
    [PERIOD_YEAR] nvarchar(4) NOT NULL DEFAULT (([dbo].[ufn_getSysParm]('PERIOD_YEAR'))),
    [DATE_CREATED] datetime NOT NULL DEFAULT ((getdate())),
    [ORDER_NUMBER] nvarchar(60) NULL,
    [IT_ISSUE] int NOT NULL,
    [ALLOCATION_RATE] numeric(22,7) NULL,
    CONSTRAINT [PK_ADJUSTMENTS_ID] PRIMARY KEY ([ADJUSTMENT_ID]) WITH (FILLFACTOR = 90)
);
GO


CREATE TABLE [DATA_NEWCOMER_SETTINGS] (
    [DATA_NEWCOMER_SETTINGS_ID] int NOT NULL IDENTITY,
    [EMPLOYEE_ROW_ID] nvarchar(15) NULL,
    [POSITION_NAME] nvarchar(50) NULL,
    [PERIOD_DURATION_IN_MONTHS] int NULL,
    [PERIOD_START_DATE] datetime NULL,
    [GUARANTEE] numeric(18,2) NULL,
    [ACTIVATED] int NULL DEFAULT 0,
    CONSTRAINT [DATA_NEWCOMER_SETTINGS_ID] PRIMARY KEY ([DATA_NEWCOMER_SETTINGS_ID]) WITH (FILLFACTOR = 90)
);
GO


CREATE TABLE [DATA_ORDER_HEADERS] (
    [DATA_ORDER_HEADERS_ID] int NOT NULL IDENTITY,
    [ORDER_ROW_ID] nvarchar(30) NULL,
    [ORDER_NUMBER] nvarchar(60) NULL,
    [SAP_ORDER_REFERENCE] nvarchar(20) NULL,
    [ORDER_TYPE] nvarchar(100) NULL,
    [PROMOTION_CODE] nvarchar(60) NULL,
    [CUSTOMER_ACCOUNT_NUMBER] nvarchar(60) NULL,
    [CUSTOMER_NAME] nvarchar(200) NULL,
    [CUSTOMER_TYPE] nvarchar(60) NULL,
    [PR_POSTN_ID] nvarchar(30) NULL,
    [ORDER_LIST_VAL] AS ([dbo].[ufn_GetListVal]([ORDER_ROW_ID])),
    [ORDER_SALE_VAL] AS ([dbo].[ufn_GetSaleVal]([ORDER_ROW_ID])),
    [ORDER_DISCOUNT_VAL] AS ([dbo].[ufn_GetDiscountVal]([ORDER_ROW_ID])),
    [ORDER_DISCOUNT_PERCENT] AS ([dbo].[ufn_GetDiscountPct]([ORDER_ROW_ID])),
    [SERVICE_LIST_VAL] AS ([dbo].[ufn_GetServiceListVal]([ORDER_ROW_ID])),
    [SERVICE_SALE_VAL] AS ([dbo].[ufn_GetServiceSaleVal]([ORDER_ROW_ID])),
    [SERVICE_DISCOUNT_VAL] AS ([dbo].[ufn_GetServiceDiscVal]([ORDER_ROW_ID])),
    [SERVICE_DISCOUNT_PERCENT] AS ([dbo].[ufn_GetServiceDiscPct]([ORDER_ROW_ID])),
    [SERVICE_TYPE] AS ([dbo].[ufn_getServiceType]([ORDER_ROW_ID])),
    [DATE_CREATED] datetime NOT NULL DEFAULT ((getdate())),
    [PERIOD_MONTH] nvarchar(2) NULL DEFAULT (([dbo].[ufn_getSysParm]('PERIOD_MONTH'))),
    [PERIOD_YEAR] nvarchar(4) NULL DEFAULT (([dbo].[ufn_getSysParm]('PERIOD_YEAR'))),
    [MAINTENANCE_TERM] nvarchar(50) NULL,
    CONSTRAINT [PK_DATA_ORDER_HEADERS_ID] PRIMARY KEY ([DATA_ORDER_HEADERS_ID]) WITH (FILLFACTOR = 90)
);
GO


CREATE TABLE [DATA_ORDER_ITEMS] (
    [DATA_ORDER_ITEMS_ID] int NOT NULL IDENTITY,
    [ORDER_ITEM_ID] nvarchar(30) NULL,
    [ORDER_ROW_ID] nvarchar(30) NULL,
    [LINE_NUMBER] int NULL,
    [PRODUCT_CODE] nvarchar(200) NULL,
    [PRODUCT_DESC] nvarchar(510) NULL,
    [LIST_VALUE] numeric(22,7) NULL,
    [SALE_VALUE] numeric(22,7) NULL,
    [QUANTITY] numeric(22,7) NULL,
    [PRODUCT_LEVEL_1] nvarchar(80) NULL,
    [PRODUCT_LEVEL_2] nvarchar(80) NULL,
    [PRODUCT_LEVEL_3] nvarchar(80) NULL,
    [PRODUCT_TYPE] nvarchar(80) NULL,
    [DATE_CREATED] datetime NOT NULL DEFAULT ((getdate())),
    CONSTRAINT [PK_DATA_ORDER_ITEMS_ID] PRIMARY KEY ([DATA_ORDER_ITEMS_ID]) WITH (FILLFACTOR = 90)
);
GO


CREATE TABLE [DATA_ORDER_POSITIONS] (
    [DATA_ORDER_POSITIONS_ID] int NOT NULL IDENTITY,
    [ORDER_ROW_ID] nvarchar(30) NULL,
    [POSITION_ROW_ID] nvarchar(30) NULL,
    [ALLOCATION_PERCENTAGE] numeric(22,7) NULL,
    [POSITION_NAME] nvarchar(100) NULL,
    [PAYPLAN_TYPE] nvarchar(60) NULL,
    [PARENT_POSITION_ROW_ID] nvarchar(30) NULL,
    [EMPLOYEE_ROW_ID] nvarchar(30) NULL,
    [DATE_CREATED] datetime NOT NULL DEFAULT ((getdate())),
    CONSTRAINT [PK_DATA_ORDER_POSITIONS_ID] PRIMARY KEY ([DATA_ORDER_POSITIONS_ID]) WITH (FILLFACTOR = 90)
);
GO


CREATE TABLE [DATA_ORDER_PROCESS_HISTORY] (
    [DATA_ORDER_PROCESS_HISTORY_ID] int NOT NULL IDENTITY,
    [ROW_ID] nvarchar(15) NULL,
    [BU_NAME] nvarchar(60) NULL,
    [REVENUE_PROCESSED] bit NULL DEFAULT CAST(0 AS bit),
    [COMMISSION_PROCESSED] bit NULL DEFAULT CAST(0 AS bit),
    [DATE_CREATED] datetime NOT NULL DEFAULT ((getdate())),
    CONSTRAINT [PK_DATA_ORDER_PROCESS_HISTORY_ID] PRIMARY KEY ([DATA_ORDER_PROCESS_HISTORY_ID]) WITH (FILLFACTOR = 90)
);
GO


CREATE TABLE [DATA_ORDER_SERVICE_ITEMS] (
    [DATA_ORDER_SERVICE_ITEMS_ID] int NOT NULL IDENTITY,
    [ORDER_ITEM_ID] nvarchar(30) NULL,
    [ORDER_ROW_ID] nvarchar(30) NULL,
    [LINE_NUMBER] int NULL,
    [PRODUCT_CODE] nvarchar(200) NULL,
    [PRODUCT_DESC] nvarchar(510) NULL,
    [LIST_VALUE] numeric(22,7) NULL,
    [SALE_VALUE] numeric(22,7) NULL,
    [QUANTITY] numeric(22,7) NULL,
    [PRODUCT_LEVEL_1] nvarchar(80) NULL,
    [PRODUCT_LEVEL_2] nvarchar(80) NULL,
    [PRODUCT_LEVEL_3] nvarchar(80) NULL,
    [PRODUCT_TYPE] nvarchar(80) NULL,
    [DATE_CREATED] datetime NOT NULL DEFAULT ((getdate())),
    CONSTRAINT [PK_DATA_ORDER_SERVICE_ITEMS_ID] PRIMARY KEY ([DATA_ORDER_SERVICE_ITEMS_ID]) WITH (FILLFACTOR = 90)
);
GO


CREATE TABLE [DATA_ORDER_STATUS_HISTORY] (
    [ROW_ID] nvarchar(15) NULL,
    [STATUS_CD] nvarchar(200) NOT NULL,
    [STATUS_DT] datetime NULL,
    [DATE_CREATED] datetime NOT NULL DEFAULT ((getdate()))
);
GO


CREATE TABLE [DATA_PERFORMANCE_AGAINST_TARGET_MATRIX] (
    [rowId] int NOT NULL IDENTITY,
    [payplan] nvarchar(5) NULL,
    [employeeId] nvarchar(50) NULL,
    [periodYear] int NULL,
    [periodMonthStart] int NULL,
    [periodMonthEnd] int NULL,
    [allocationId] int NULL,
    [targetPercentageStart] int NULL,
    [targetPercentageEnd] int NULL,
    [commissionValue] numeric(18,5) NULL,
    [IS_MANAGER] int NULL DEFAULT 0
);
GO


CREATE TABLE [DATA_POSITION_HISTORY] (
    [DATA_POSITION_HISTORY_ID] int NOT NULL IDENTITY,
    [EMPLOYEE_ROW_ID] nvarchar(30) NULL,
    [POSITION_ROW_ID] nvarchar(30) NULL,
    [POSITION_NAME] nvarchar(200) NULL,
    [START_DT] datetime NULL,
    [END_DT] datetime NULL,
    [PARENT_ROW_ID] nvarchar(30) NULL,
    [X_REP_TYPE] nvarchar(60) NULL,
    [DATE_CREATED] datetime NOT NULL DEFAULT ((getdate())),
    CONSTRAINT [PK_DATA_POSITION_HISTORY_ID] PRIMARY KEY ([DATA_POSITION_HISTORY_ID]) WITH (FILLFACTOR = 90)
);
GO


CREATE TABLE [DATA_PRODUCTS_INCLUDED] (
    [DATA_PRODUCTS_INCLUDED_ID] int NOT NULL IDENTITY,
    [ITEM_ID] nvarchar(30) NULL,
    [PRODUCT_DESC] nvarchar(500) NULL,
    [PRODUCT_CODE] nvarchar(30) NULL,
    [PRODUCT_LEVEL_1] nvarchar(20) NULL,
    [PRODUCT_LEVEL_2] nvarchar(20) NULL,
    [PRODUCT_LEVEL_3] nvarchar(20) NULL,
    [PRODUCT_TYPE] nvarchar(80) NULL,
    [INCLUDED] int NULL DEFAULT 1,
    [LEVEL_BASED] int NULL DEFAULT 0,
    [ALLOCATION_ID] int NULL,
    CONSTRAINT [PK_DATA_PRODUCTS_INCLUDED] PRIMARY KEY ([DATA_PRODUCTS_INCLUDED_ID])
);
GO


CREATE TABLE [DATA_PRODUCTS_UNKNOWN] (
    [DATA_PRODUCTS_UNKNOWN_ID] int NOT NULL IDENTITY,
    [PRODUCT_DESC] nvarchar(700) NULL,
    [PRODUCT_CODE] nvarchar(50) NULL,
    [PRODUCT_LEVEL_1] nvarchar(50) NULL,
    [PRODUCT_LEVEL_2] nvarchar(50) NULL,
    [PRODUCT_LEVEL_3] nvarchar(50) NULL,
    CONSTRAINT [PK_DATA_PRODUCTS_UNKNOWN] PRIMARY KEY ([DATA_PRODUCTS_UNKNOWN_ID])
);
GO


CREATE TABLE [OrdersToProcess] (
    [id] int NOT NULL IDENTITY,
    [order_id] nvarchar(50) NULL,
    [status_dt] datetime NULL
);
GO


CREATE TABLE [PAYPLAN_UNSET] (
    [PAYPLAN_UNSET_ID] int NOT NULL IDENTITY,
    [PAYPLAN] nvarchar(10) NULL,
    [ORDERID] nvarchar(30) NOT NULL,
    CONSTRAINT [PK_FPSM_ALLOCATION_ID] PRIMARY KEY ([PAYPLAN_UNSET_ID])
);
GO


CREATE TABLE [RUN_ICM_INFO] (
    [RUN_ICM_INFO_ID] int NOT NULL IDENTITY,
    [BEGIN_DATE] datetime NULL DEFAULT ((getdate())),
    [END_DATE] datetime NULL,
    [STATUS] nvarchar(30) NULL,
    CONSTRAINT [PK_RUN_ICM_INFO] PRIMARY KEY ([RUN_ICM_INFO_ID])
);
GO


CREATE TABLE [SYSTEM_LOG] (
    [SYSTEM_LOG_ID] int NOT NULL IDENTITY,
    [LOG_SOURCE] nvarchar(4000) NULL,
    [LOG_DESC] nvarchar(max) NULL,
    [REFERENCE_TYPE] nvarchar(4000) NULL,
    [REFERENCE_VALUE] nvarchar(4000) NULL,
    [LOG_CATEGORY] nvarchar(100) NULL,
    [LOG_DATETIME] datetime NULL DEFAULT ((getdate())),
    [LOG_COUNT_ID] int NULL,
    CONSTRAINT [PK_SYSTEM_LOG_ID] PRIMARY KEY ([SYSTEM_LOG_ID]) WITH (FILLFACTOR = 90)
);
GO


CREATE TABLE [TMP_DATA_EMPLOYEES] (
    [TMP_DATA_EMPLOYEES_ID] int NOT NULL IDENTITY,
    [ROW_ID] nvarchar(30) NULL,
    [FST_NAME] nvarchar(100) NULL,
    [LAST_NAME] nvarchar(100) NULL,
    [EMAIL_ADDR] nvarchar(200) NULL,
    [JOB_TITLE] nvarchar(150) NULL,
    [EMPLOYEE_NUMBER] nvarchar(100) NULL,
    [PR_HELD_POSTN_ID] nvarchar(30) NULL,
    [LOGIN] nvarchar(100) NULL,
    CONSTRAINT [PK_TMP_DATA_EMPLOYEES_ID] PRIMARY KEY ([TMP_DATA_EMPLOYEES_ID]) WITH (FILLFACTOR = 90)
);
GO


CREATE TABLE [TMP_DATA_IMPRESS_SUBSCRIPTION_ORDER] (
    [DATA_IMPRESS_SUBSCRIPTION_ORDER_ID] int NOT NULL IDENTITY,
    [IM_ORDER_NUMBER] nvarchar(50) NULL,
    [SF_ORDER_NUMBER] nvarchar(50) NULL,
    [IM_ACCOUNT_NAME] nvarchar(50) NULL,
    [IM_ACCOUNT_NUMBER] nvarchar(50) NULL,
    [IM_PLAN_NAME] nvarchar(50) NULL,
    [IM_PLAN_TIER] nvarchar(50) NULL,
    [SF_EMPLOYEE_ID] nvarchar(50) NULL,
    [SF_SUBSCRIPTION_MONTHS_AMOUNT] int NULL,
    [SF_ANTICIPATED_USAGE] numeric(7,2) NULL,
    [SF_SUBSCRIPTION_PRICE] numeric(7,2) NULL,
    [SF_ORDER_STATUS] nvarchar(150) NULL,
    [SF_LAST_STATUS_UPDATE_TIME] datetime NULL,
    [IM_PRICE_PER_USAGE_ITEM] numeric(7,2) NULL,
    [IM_ACTUAL_USAGE] int NULL
);
GO


CREATE TABLE [TMP_DATA_ORDER_HEADER] (
    [TMP_DATA_ORDER_HEADER_ID] int NOT NULL IDENTITY,
    [ROW_ID] nvarchar(30) NULL,
    [ORDER_NUMBER] nvarchar(60) NULL,
    [ACCOUNT_NUMBER] nvarchar(60) NULL,
    [SAP_REFERENCE] nvarchar(20) NULL,
    [PROMOTION_CODE] nvarchar(60) NULL,
    [CUSTOMER_NAME] nvarchar(200) NULL,
    [CUSTOMER_TYPE] nvarchar(60) NULL,
    [ORDER_TYPE] nvarchar(100) NULL,
    [PR_POSTN_ID] nvarchar(30) NULL,
    [MAINTENANCE_TERM] nvarchar(50) NULL,
    CONSTRAINT [PK_TMP_DATA_ORDER_HEADER] PRIMARY KEY ([TMP_DATA_ORDER_HEADER_ID]) WITH (FILLFACTOR = 90)
);
GO


CREATE TABLE [TMP_DATA_ORDER_ITEM] (
    [TMP_DATA_ORDER_ITEM_ID] int NOT NULL IDENTITY,
    [ORDER_ITEM_ID] nvarchar(30) NULL,
    [ORDER_ROW_ID] nvarchar(30) NULL,
    [LINE_NUMBER] int NULL,
    [PRODUCT_CODE] nvarchar(200) NULL,
    [PRODUCT_DESC] nvarchar(510) NULL,
    [LIST_VALUE] numeric(22,7) NULL,
    [SALE_VALUE] numeric(22,7) NULL,
    [QUANTITY] numeric(22,7) NULL,
    [PRODUCT_LEVEL_1] nvarchar(80) NULL,
    [PRODUCT_LEVEL_2] nvarchar(80) NULL,
    [PRODUCT_LEVEL_3] nvarchar(80) NULL,
    [PRODUCT_TYPE] nvarchar(80) NULL,
    CONSTRAINT [PK_TMP_DATA_ORDER_ITEM_ID] PRIMARY KEY ([TMP_DATA_ORDER_ITEM_ID]) WITH (FILLFACTOR = 90)
);
GO


CREATE TABLE [TMP_DATA_ORDER_REPS] (
    [TMP_DATA_ORDER_REPS_ID] int NOT NULL IDENTITY,
    [ORDER_POS_ID] nvarchar(30) NULL,
    [ROW_ID] nvarchar(30) NULL,
    [POSITION_ID] nvarchar(30) NULL,
    [ALLOCATION_PERC] numeric(22,7) NULL,
    CONSTRAINT [PK_TMP_DATA_ORDER_REPS_ID] PRIMARY KEY ([TMP_DATA_ORDER_REPS_ID]) WITH (FILLFACTOR = 90)
);
GO


CREATE TABLE [TMP_DATA_ORDER_STATUS_HISTORY] (
    [TMP_DATA_ORDER_STATUS_HISTORY_ID] int NOT NULL IDENTITY,
    [rowId] nvarchar(15) NULL,
    [buName] nvarchar(60) NULL,
    [dateCreated] datetime NOT NULL,
    CONSTRAINT [PK_TMP_DATA_ORDER_STATUS_HISTORY_ID] PRIMARY KEY ([TMP_DATA_ORDER_STATUS_HISTORY_ID]) WITH (FILLFACTOR = 90)
);
GO


CREATE TABLE [TMP_DATA_POSITIONS] (
    [TMP_DATA_POSITIONS_ID] int NOT NULL IDENTITY,
    [ROW_ID] nvarchar(30) NULL,
    [POSITION_NAME] nvarchar(100) NULL,
    [END_DT] datetime NULL,
    [START_DT] datetime NULL,
    [PR_EMP_ID] nvarchar(30) NULL,
    [X_REP_TYPE] nvarchar(60) NULL,
    [PARENT_ROW_ID] nvarchar(30) NULL,
    CONSTRAINT [PK_TMP_DATA_POSITIONS_ID] PRIMARY KEY ([TMP_DATA_POSITIONS_ID]) WITH (FILLFACTOR = 90)
);
GO


CREATE UNIQUE INDEX [_unique_CONFIG_SYSTEM_PARAMETERS] ON [CONFIG_SYSTEM_PARAMETERS] ([PARAMETER_NAME], [PARAMETER_VALUE]) WHERE [PARAMETER_VALUE] IS NOT NULL WITH (FILLFACTOR = 90);
GO


CREATE INDEX [IX_CSP_PARAMETER_NAME] ON [CONFIG_SYSTEM_PARAMETERS] ([PARAMETER_NAME]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [IX_DBU_BU_NAME] ON [DATA_BUSINESS_UNIT] ([BU_NAME]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [IX_DBU_ORDER_ID] ON [DATA_BUSINESS_UNIT] ([ORDER_ID]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [IX_DCP_PAYMENT_SOURCE_VALUES] ON [DATA_COMMISSION_PAYMENT] ([PERIOD_YEAR], [PERIOD_MONTH], [PAYMENT_SOURCE], [PAYMENT_VALUE]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [IX_DCA_ACHIEVEMENT] ON [DATA_CREDIT_ALLOCATION] ([EMPLOYEE_ID], [ALLOCATION_TYPE_ID], [PERIOD_MONTH], [PERIOD_YEAR], [EXCLUDE_FROM_CALCS], [ALLOCATION_LIST], [ALLOCATION_VALUE]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [IX_DCA_ADJUSTMENT_ID] ON [DATA_CREDIT_ALLOCATION] ([ADJUSTMENT_ID]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [IX_DCA_ALLOCATION_SOURCE] ON [DATA_CREDIT_ALLOCATION] ([ALLOCATION_SOURCE]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [IX_DCA_ALLOCATION_TYPE_ID] ON [DATA_CREDIT_ALLOCATION] ([ALLOCATION_TYPE_ID]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [IX_DCA_ALLOCATION_TYPE_ID_PERIOD_MONTH_PERIOD_YEAR] ON [DATA_CREDIT_ALLOCATION] ([ALLOCATION_TYPE_ID], [PERIOD_MONTH], [PERIOD_YEAR]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [IX_DCA_EMPLOYEE_ID] ON [DATA_CREDIT_ALLOCATION] ([EMPLOYEE_ID], [ALLOCATION_TYPE_ID], [ALLOCATION_VALUE], [PERIOD_MONTH], [PERIOD_YEAR], [EXCLUDE_FROM_CALCS], [POSITION_ID]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [IX_DCA_ITEM_ID] ON [DATA_CREDIT_ALLOCATION] ([ITEM_ID]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [IX_DCA_ORDER_ID] ON [DATA_CREDIT_ALLOCATION] ([ORDER_ID]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [IX_DCA_ORDERS_EMPLOYEES] ON [DATA_CREDIT_ALLOCATION] ([ALLOCATION_TYPE_ID], [ORDER_ID], [EMPLOYEE_ID], [POSITION_ID]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [IX_DCA_PERIOD_YEAR] ON [DATA_CREDIT_ALLOCATION] ([PERIOD_YEAR]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [IX_DCA_POSITION_ID] ON [DATA_CREDIT_ALLOCATION] ([POSITION_ID]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [IX_DCA_ROLLUP] ON [DATA_CREDIT_ALLOCATION] ([ROLLUP_PROCESSED], [DATA_CREDIT_ALLOCATION_ID]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [idx_DATA_EMPLOYEES_ROW_ID] ON [DATA_EMPLOYEES] ([ROW_ID]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [IX_DATA_ORDER_HEADERS_CUSTOMER_ACCOUNT_NUMBER] ON [DATA_ORDER_HEADERS] ([CUSTOMER_ACCOUNT_NUMBER]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [IX_DATA_ORDER_HEADERS_DATE_CREATED] ON [DATA_ORDER_HEADERS] ([DATE_CREATED]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [IX_DATA_ORDER_HEADERS_ORDER_NUMBER] ON [DATA_ORDER_HEADERS] ([ORDER_NUMBER]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [IX_DATA_ORDER_HEADERS_ORDER_ROW_ID] ON [DATA_ORDER_HEADERS] ([ORDER_ROW_ID]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [IDX_DATA_ORDER_ITEMS_ORDER_ITEM_ID] ON [DATA_ORDER_ITEMS] ([ORDER_ITEM_ID]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [IDX_DATA_ORDER_ITEMS_PRODUCT_CODE] ON [DATA_ORDER_ITEMS] ([PRODUCT_CODE]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [IDX_DATA_ORDER_ITEMS_PRODUCT_LEVEL_1] ON [DATA_ORDER_ITEMS] ([PRODUCT_LEVEL_1]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [IDX_DATA_ORDER_ITEMS_PRODUCT_LEVEL_2] ON [DATA_ORDER_ITEMS] ([PRODUCT_LEVEL_2]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [IDX_DATA_ORDER_ITEMS_PRODUCT_LEVEL_3] ON [DATA_ORDER_ITEMS] ([PRODUCT_LEVEL_3]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [IX_DATA_ORDER_HEADERS_ORDER_ROW_ID] ON [DATA_ORDER_ITEMS] ([ORDER_ROW_ID]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [IDX_DATA_ORDER_POSITIONS_ORDER_ROW_ID] ON [DATA_ORDER_POSITIONS] ([ORDER_ROW_ID]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [idx_DATA_ORDER_PROCESS_HISTORY_BU_NAME] ON [DATA_ORDER_PROCESS_HISTORY] ([BU_NAME]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [idx_DATA_ORDER_PROCESS_HISTORY_COMMISSION_PROCESSED] ON [DATA_ORDER_PROCESS_HISTORY] ([COMMISSION_PROCESSED]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [idx_DATA_ORDER_PROCESS_HISTORY_ROW_ID] ON [DATA_ORDER_PROCESS_HISTORY] ([ROW_ID]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [IX_DATA_ORDER_SERVICE_ITEMS_ORDER_ROW_ID] ON [DATA_ORDER_SERVICE_ITEMS] ([ORDER_ROW_ID]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [idx_DATA_ORDER_STATUS_HISTORY_ROW_ID] ON [DATA_ORDER_STATUS_HISTORY] ([ROW_ID]) WITH (FILLFACTOR = 90);
GO


CREATE CLUSTERED INDEX [IDX_DATA_ORDER_STATUS_HISTORY_ROW_ID_STATUS_DT] ON [DATA_ORDER_STATUS_HISTORY] ([ROW_ID], [STATUS_DT]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [idx_DATA_ORDER_STATUS_HISTORY_STATUS_CD] ON [DATA_ORDER_STATUS_HISTORY] ([STATUS_CD]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [idx_DATA_ORDER_STATUS_HISTORY_STATUS_DT] ON [DATA_ORDER_STATUS_HISTORY] ([STATUS_DT]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [IX_TMP_DATA_ORDER_HEADER_ORDER_TYPE] ON [TMP_DATA_ORDER_HEADER] ([ORDER_TYPE], [ROW_ID]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [IX_TMP_DATA_ORDER_HEADER_ROW_ID] ON [TMP_DATA_ORDER_HEADER] ([ROW_ID]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [IX_TMP_DATA_ORDER_ITEM_ORDER_ROW_ID] ON [TMP_DATA_ORDER_ITEM] ([ORDER_ROW_ID]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [idx_TMP_DATA_ORDER_REPS_ORDER_POS_ID] ON [TMP_DATA_ORDER_REPS] ([ORDER_POS_ID]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [idx_TMP_DATA_ORDER_REPS_ROW_ID] ON [TMP_DATA_ORDER_REPS] ([ROW_ID]) WITH (FILLFACTOR = 90);
GO


CREATE INDEX [missing_index_1113] ON [TMP_DATA_POSITIONS] ([ROW_ID]) WITH (FILLFACTOR = 90);
GO


